sudo: false
language: node_js
node_js:
- 4.2.6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
script:
- npm run build && npm test && cat ./coverage/lcov.info | ./node_modules/.bin/codecov
- chmod 755 ${TRAVIS_BUILD_DIR}/deploy.sh && sh -c "${TRAVIS_BUILD_DIR}/deploy.sh"
before_install:
- export CC="gcc-4.9" CXX="g++-4.9"
install:
- npm install
env:
  global:
    secure: pL9O2VFziHNToD2FW+eZJcZNCEl2ltL7WuTa2aZro4XFjiU30JfY/nTD1hLcPDd+ZgS8gg/+OREHs2GCxsmzOpyLZNj4mR9/jNdfCwwGZrf/oJzjZjBWNzEqgTTrZTGKji4/XonVfVg0wU7sqv+SNpWOhdsfr9NZBnOYSs7vMcmqdhCiILGJIGMqBj37ux5tgtGJJkxR+IHwJKQe634S+HzNuCXaTJ2U1a6pCz9tb25Y8vFQ9rOPd2iZVd7GoNccDAzHGWNBuiRxxETE4Mn6VmHiaAccJ181kcKJ01S0bjoALbX9L5ySKqDLPfs2dKOJdrvGwWfMhZYkXWJGelIzOHUtSBcxYQ4ZfXWpLKbd169EeEwEC9tC6E4h3SaKddUiP+aVzC2zsh+WNag/xIDT+a3uXdDRSieNAL3cCh/45bFyo5BXRxSJamVRVBTuhaAvVGxRjuIc1qBiLKnNXTnkVFmEtnmoPmeaNWvBaGvqvhKOERJXGRCnB3mXaTTgdDEAXfHHdHgLQc0NfS/VgW9qGFJQklCHV15/MJ06+f8od/FeE+/s3FsrFxSD3qxuLvvOUYzYCQUeXI8Q6WfX6vwU9UYsSpDhkmV1k5Eg/1oZeYo+pVI94L3LhtwGw/ZCWeTR9IEFOmZQX66i/4BAfU2xyKkXMLaBOeWd8v9/QCbLacQ=
deploy:
  provider: npm
  skip_cleanup: true
  email: support@kuzzle.io
  api_key:
    secure: fyAUrBhmctUri2wPCcdufPME6EyFLpC4OS4wMAmUc7iNNSUl2C9On0HMkmz1JKD/+fMhlFCvQcpD6O8hNThneSqrv/PANAyz9YXblv35W9v1XbYrzm5IWQ4D30+Zg350SK6Wqn4Wr6jZkRXQKhBo8GQ5aLsDdhr7RgRBpw8p6GwDuda41K9cAOh8vbX2u6guOfeJW+jfwfXgwZUl/DEor8XkIJYcVwOF0989FT0urYf28afnxVgaj5XuIyNQMLC0R0KAsbYO0EPDy1O7a34SFUoNVBXPqP+5wYocML6mKNOFtLfvTAfIeErQc6Is3roJvZqMkcu8zzRH+OdbQfa+3+sUTPbxBAaNvcITO/z36QnYh/Swbnfxn0dD5ue2bAXseVpa55fWw0DPOQkcQ3VJ9hHQfMWTn+4EH6lqYEynSJ0KGbHqzm3Qm15fCj0s+vjvs4axGcYEpZlJaTu9o3oHYJTTDfbkk4b7nbKGQ/vDsYFTRL2yRprYlCQ8YoUnDMOB3YHxmRs7Jgxb9lbg8iD5ZMtP1+QIhUMJTI16ruxs88bRvCaTkfdTOGv0qVhgA9a00+G1XMLxCzpvI8wKgo7+GKRPUyvR2bRCQS6mHtbp6beCqPxgzyfGzg8XU09disST7spqH3E8ohWwVfgkjoBlS9+y62iaiwXRsTVXyeGJpac=
  on:
    repo: kuzzleio/sdk-javascript
    branch: master
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
  slack:
    secure: m0BEda/eXxYkil0zDZ1uNpK13kiNbb5/80I5OqDBz6X7/WH3uhWIV6q38lI929tQKz04eHAfVDaRSoPk1XwZBnb70MgcRmSG/m4/moR7BCnx7D9hHFqhNf0EfdzwEg44dCCVtD2vUvChtYV+jK74sNd4yqeq86YXi33qS7SYLS6kYnRloX0D7sQXDy14FWU2a5+hsrPX8yBoWuPjBergvK6W1dZAG+SfDywaqsrUDs+q64yEHiYV9VlvVZ/oKXZiDnVcB2hi0uulIZ8+iZaMJFEU30uCQiK6w3HG587yx3sVJmprr64ZYHKaFJD2ZAG1td6wJ1ccJsU/ruGkj4+0CeoZUYYBYXYQ4qhQl8F2QT0m+8dWqPwzYpxEoqyvGS9ioZG/YI18V2CE1pEyc72JzEv6c3AgDbtwrLH5s3ViNts7kulk3wwCzuAww+DapSV9ggezo+Bs7OGRpXwh/saeKWUCLqTkLQTjuq2dFVdo85HsC2RrLcSsZLMTOuV/A//FNBDJBlNnuneGP84zGkWGPEja0FFXvm2TS95gh1hd2PMe+QxjygOAvIMLmDmfdlWSLayUeWbqp20EdF7TUHV0dvBucga8s3UvFhIMnnGLS9vcNEIRtVornXznwdYSLbYD0mLXNtitneXTnSAxilThKtGDPOWQFkYkyoFV9FEwKO8=
    on_success: never
    on_failure: always
    on_start: never
