sudo: true

jobs:
  include:
    - stage: Tests
      name: Unit Tests
      if: type = pull_request OR type = push AND branch =~ /^master|[0-9]+-(dev|stable)$/ OR type = cron
      language: node_js
      node_js: 6

      env:
        # Codecov token
        secure: ATb4QFGG6sPkfquAoye6BeN7u4uQ4abP8qatVK8XG3Qof+pECZwRkFPVoopO1Gb/4bQSPfapc1aGPzGuKi409v633vpDnpcgM7cHX9CPT+YQYcTePMFtq/m+5YY3WIYWM1zCFmJ+bBwQO/MtsubfGfA9EmSAAxtnJV+1JDD3Y6+NQRkQN7K+gxQozec0u1W0Oe1sJXLSKlW3JPL8iRtKcLvmIDysKtBK6X/Wg1qP2Me4reb449a0yGej3QvZDbDYJbdlh7vuFLjXJAz3yExfED8QAm8wf0p9F8emILHnkLxjumTTnGUUqDJLLu8WgkahFiyFo4jMtryhNQ0+p6WhXmEbpNIO+yMGSZPsCGbnpkhWJ1aMAT6ZhgpHf4jDZQd4ZJi02+n9tOpe+Lm2Jk2LXY8SwMk3xGtqm5sk03weTc019TUGj/NLoHNjO/vfNz3xOImD5Gck3bXWNxdrX3bjiyVsr/u77enoWu9drPCEl3JOTIwVP3mTF8R3axSFOQ8M4SI1orCMChkGMB5qExl+Gfx+MHa/jL7QKO1SFRgl1O3DbhsyFE6xiabYzwLcdbI50ypy6VJjmDd5RxK7BkDa8RumlHT1uY1FK9yRXu4XFrrw9FjF2s+xjWbliRZqXRReXk0W1Hz4zj5au3Y9YH5a/UPtB72TY+AUUWHTUPQl3SU=

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9

      before_install:
        - export CC="gcc-4.9" CXX="g++-4.9"

      install:
        - npm install
        - npm run build

      script:
        - npm run lint
        - npm run unit-testing

      after_success:
        - cat ./coverage/lcov.info | ./node_modules/.bin/codecov
        - chmod 755 ${TRAVIS_BUILD_DIR}/deploy.sh && sh -c "${TRAVIS_BUILD_DIR}/deploy.sh"

    - stage: Tests
      name: Dead link check
      if: type = pull_request OR type = push AND branch =~ /^master|[0-9]+-(dev|stable)$/ OR type = cron

      before_script:
        - npm run doc-prepare
        - npm run --prefix doc/framework clone-repos
      script:
        - npm run --prefix doc/framework dead-links


    - stage: Deployment Doc Dev
      name: Deploy next-docs.kuzzle.io
      if: branch = 5-dev
      language: node_js
      node_js: 10
      env:
        - NODE_ENV=production
        - S3_BUCKET=docs-next.kuzzle.io
        - CLOUDFRONT_DISTRIBUTION_ID=E2ZCCEK9GRB49U
        - AWS_DEFAULT_REGION=us-west-2
        # AWS_ACCESS_KEY_ID
        - secure: "0VUGNqpM0z8WGMaD3ZqgV878x8Zxfh753Ox4s4cgBldk1lcTD1DzoCJuk6uzIeOIZkYEyq5APmW5V0hqB3l3lswAoVi/QieJ8VPh6axmcrDo4s2aekDhLR00zIlS6hcVoCjeOcbgxw/vWXEeNbTW5gF6XJcbhHRjT6MbudIGvxxBg84Yyt7lMUmqBOWtNyWpQPuuUKnUDubvoMlmjbbaSfllH6f83zNaGDyygUiRkuSeQRK5GKK1/lcloQBantSm+JPwCUm9TKQyU6AXH4vdvKRdiCO1lhYBa9Eealab71lLPqRJt8tKZqCeYx7ou4FByZpGQ78/rvq0Mr/nfFZA7ECrBJIDd3QYl2mFhwaHVs8VyikIKR/ZaaZ38iw1ISEIVmMH5aTlACv8725T5o2Ej1jcYXdOityf9M0u/FhmqYLnOB6RyES+YMfKBcQ3ULC+pHzJYM5ExzvIw45P82XVEq97whLHGA41nAgcKUsdzMy95a2BI/tIGK4S9BN/P8sbx0kvTeBgLwBqy7CgUKX674strMwHQ8sLylztU4jM62dMo0+Rhw3dLMQ8fkSjCyKRP78BX0ic9uB0Kk5ZhcnjdH/f9L4bjjwvUUZvEbeFtDSDVdxgmurjqxrpDiqfETQ7f4KUia8tzApRuHkdJGFOIcNf22DxursmN8dMJzIGNRw="
        # AWS_SECRET_ACCESS_KEY
        - secure: "HU48VGBdv/GyVAm6g8eiA3DbKoAPL98AeORbF7UhKLQenxmQRGb1gfdMPNLdop35+95SlxcFC9ogoHcqLBSPLLcTSX57faWpNacD/7j69Z03avgdmfaFOGMOwGd5tOdq4pYmis34xyGJW1kpwAl2U6jp/pcBXABDnCLfRS5kJUsXvrwdE75UACoXQ1tXEtqq9y5LcFo/dGYrhuVvqYQmAUA+ExrfXaIKtUSf2tN5CvYL0cSxLyoQlnbbIQvouyNRyfuGFqNHc3jyBOc/nZWHS0ES91+6ddwZs/i9Fs98TfB3JS9x+gKYWrhDmxek/fOy22+qYUHQ81txk4SQ3GILWiWTfWOTdsBU+Y0FYnC5syLAqpdIstBhmMUUS8NWs5HdYmBv4q0zkTiwBGL/wrLwXkAcLLKUNOrUeMAL1fjQuVRC3hzql15s/A2LwPOR6xwyCu1mH8GKogYulGVWOEHQuk8bC3MaKgDr/4ZoUlCC9Q+mYP/WT+t/NA/0OQIvZVhVVilXk1MTbQMkvrBSuiuxACsyFGVNrkLaC8x2Pjyd2kgZaIv4c2JiiWfvW5IZd7xeyLLKESOfHP8rIf60jmvE7hxD9Yje7JXjo0uvnpEGx2PuMSq5zeUynoLaa8AIMAJ9an3fgdfKKcZ/XPOCAgpmxnKH+leAQx86qwxdAAIkgPY="

      addons:
        apt:
          packages:
            - python
            - python-pip

      install:
        - pip install awscli --upgrade --user

      script:
        - npm run doc-prepare
        - npm run doc-build

      deploy:
        provider: script
        script:
          - npm run doc-upload
        skip_cleanup: true
        on:
          branch: 5-dev

      after_deploy:
        - npm run doc-cloudfront

    - stage: Deployment Doc Prod
      name: Deploy docs.kuzzle.io
      if: branch = 5-stable
      language: node_js
      node_js: 10
      env:
        - NODE_ENV=production
        - S3_BUCKET=docs.kuzzle.io
        - CLOUDFRONT_DISTRIBUTION_ID=E3D6RP0POLCJMM
        - AWS_DEFAULT_REGION=us-west-2
        # AWS_ACCESS_KEY_ID
        - secure: "0VUGNqpM0z8WGMaD3ZqgV878x8Zxfh753Ox4s4cgBldk1lcTD1DzoCJuk6uzIeOIZkYEyq5APmW5V0hqB3l3lswAoVi/QieJ8VPh6axmcrDo4s2aekDhLR00zIlS6hcVoCjeOcbgxw/vWXEeNbTW5gF6XJcbhHRjT6MbudIGvxxBg84Yyt7lMUmqBOWtNyWpQPuuUKnUDubvoMlmjbbaSfllH6f83zNaGDyygUiRkuSeQRK5GKK1/lcloQBantSm+JPwCUm9TKQyU6AXH4vdvKRdiCO1lhYBa9Eealab71lLPqRJt8tKZqCeYx7ou4FByZpGQ78/rvq0Mr/nfFZA7ECrBJIDd3QYl2mFhwaHVs8VyikIKR/ZaaZ38iw1ISEIVmMH5aTlACv8725T5o2Ej1jcYXdOityf9M0u/FhmqYLnOB6RyES+YMfKBcQ3ULC+pHzJYM5ExzvIw45P82XVEq97whLHGA41nAgcKUsdzMy95a2BI/tIGK4S9BN/P8sbx0kvTeBgLwBqy7CgUKX674strMwHQ8sLylztU4jM62dMo0+Rhw3dLMQ8fkSjCyKRP78BX0ic9uB0Kk5ZhcnjdH/f9L4bjjwvUUZvEbeFtDSDVdxgmurjqxrpDiqfETQ7f4KUia8tzApRuHkdJGFOIcNf22DxursmN8dMJzIGNRw="
        # AWS_SECRET_ACCESS_KEY
        - secure: "HU48VGBdv/GyVAm6g8eiA3DbKoAPL98AeORbF7UhKLQenxmQRGb1gfdMPNLdop35+95SlxcFC9ogoHcqLBSPLLcTSX57faWpNacD/7j69Z03avgdmfaFOGMOwGd5tOdq4pYmis34xyGJW1kpwAl2U6jp/pcBXABDnCLfRS5kJUsXvrwdE75UACoXQ1tXEtqq9y5LcFo/dGYrhuVvqYQmAUA+ExrfXaIKtUSf2tN5CvYL0cSxLyoQlnbbIQvouyNRyfuGFqNHc3jyBOc/nZWHS0ES91+6ddwZs/i9Fs98TfB3JS9x+gKYWrhDmxek/fOy22+qYUHQ81txk4SQ3GILWiWTfWOTdsBU+Y0FYnC5syLAqpdIstBhmMUUS8NWs5HdYmBv4q0zkTiwBGL/wrLwXkAcLLKUNOrUeMAL1fjQuVRC3hzql15s/A2LwPOR6xwyCu1mH8GKogYulGVWOEHQuk8bC3MaKgDr/4ZoUlCC9Q+mYP/WT+t/NA/0OQIvZVhVVilXk1MTbQMkvrBSuiuxACsyFGVNrkLaC8x2Pjyd2kgZaIv4c2JiiWfvW5IZd7xeyLLKESOfHP8rIf60jmvE7hxD9Yje7JXjo0uvnpEGx2PuMSq5zeUynoLaa8AIMAJ9an3fgdfKKcZ/XPOCAgpmxnKH+leAQx86qwxdAAIkgPY="

      addons:
        apt:
          packages:
            - python
            - python-pip

      install:
        - pip install awscli --upgrade --user

      script:
        - npm run doc-prepare
        - npm run doc-build

      deploy:
        provider: script
        script:
          - npm run doc-upload
        skip_cleanup: true
        on:
          branch: 5-stable

    - stage: Deploy Stable release on NPM
      if: branch = master AND tag IS present AND type != cron
      sudo: false
      language: node_js
      node_js: 8

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9

      before_install:
        - export CC="gcc-4.9" CXX="g++-4.9"

      install:
        - npm install

      script:
        - npm run build

      deploy:
        provider: npm
        skip_cleanup: true
        email: support@kuzzle.io
        api_key:
          secure: HhVL7t3f2AmIN89caY9OWpUxmqYxVbr6EvdSxO7+BQOEBE1sYoxBoU9LyrKCmZS1cb4lU2GOJd3UIyB8c8VYeFpMbywwk7ZPYPsraQPDFV6Wym7l+KmV5QWhad/1yeou/FM4IDYjYb2Ais6gwD5e/0Ow4o7nIZshMuELnxDVKVTuJsViwsMMNSEvmVYvMKoWpZm5eG0emYnzWezSKB5hK1ayczpYvE0pLmySu/b7WwJ9/2pPnM70cCvIK/gFKv0aNOzX7Or5c8hdA87M7BowfnRSgsyTyi0wQN0Oj2lSsxEcAYrP+WlegX6kX8O8o9974obqDR2S5tiiPniyqT8jgwPmuiiMvn82umUks4cb355QEPHlrO9aNNXbz9VyASjJ/tyCtTDd0J3gASiEImALc4h4YfM5u8WxpNVUwsfnRdpNUM4gWy5yHVRyPxsFajYCbcz4rYgpKdDO5ZWlZ3DOJuR4aO0QLsr/pL7e+w01kO6BK+4eG7jMS8Hb3ortg2pfqnLqIinWARIHoL4cQ4aG90Y4h0ne3MvmCgNbQKQR1VkzRg1CUKdYN5IJ2Ivf/ZJ8qL6+O2N0BNRQT64PBmECNgcf+IIkdR7LcwachFfFcX43ZvxT588e0usRnU1wfB3cQaGTWPzMw2tXXuikObbthK9Xkr0w7gDV3feejuYpmDc=
        on:
          repo: kuzzleio/sdk-javascript
          all_branches: true
          condition: $TRAVIS_BRANCH = 5-stable
