sudo: false
language: node_js
node_js:
- '4.2'
script:
- grunt
before_install: npm install -g grunt-cli
install: npm install
after_success:
- if [ "${TRAVIS_BRANCH}" = "master" ]; then git config --global user.email "support@kuzzle.io";
  fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then git config --global user.name "Travis
  CI"; fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then  git clone --quiet --branch=browser https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}
  travis-build > /dev/null; fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then  cp -rp browser/* travis-build/ && cd
  travis-build ; fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then  git commit -am "Travis CI auto-merge
  from travis build ${TRAVIS_BUILD_NUMBER}"; fi
- if [ "${TRAVIS_BRANCH}" = "master" ]; then  git push -fq origin browser > /dev/null;
  fi
env:
  global:
    secure: EZ+XXJFDtehmag7wt8JbutqgzpkkJUCzkEWw6W+p7MIxWenLyuGv/RUu7KGqAloOud1cZbmZGSfRx/vsPvxRjo+ZC7aaPqb74qRvfctGdlJTtEffS2jFno1pEppJzCR4n7vocSfMVYtOD6oHP67lXwn/Qnh++WUkZaV137m5+7rqiYgJ+JTeSs5jBRZ6X7VNoNz8tZXejQ+FOymCFQTS2JM/rSZX9NEK+OwUEhEjRcxqWMm2avk6NAQNAL3WQuIBJQH8lxEJxOXkMc0rQZZ09AoLpqJKzsaicaZMInt5JstPo2e9vJfhi+PpRSNhErIff36aCHWRYYDPKl5x6IelZpBfZeTdrs4V2TbRi1y0ELbgMG1FHS4HAw3vTnh4/49g01lAJed4UguFRc6MzwTLAL8uPG/zFe8snm9+kaf4pL7yO89Hf3eltE03+N//tyVv+X/jdSca2dBZ9FMeLE5pJ2jlRiKitCLjXmLUEMMxEwNF7K/IvOrD9wue3JXK0UogOpcXfppk++pNTijsZluU1Yj7k3fGFeS8d6rIU0Yj40y6/VMaJeL4EXlARRsGLigUKVjQL6+/N5xudlsCng+EG+WVIy4wEEPH0QgjUkPTgWx1NrUlTwjskE0cdqDOBu39WkRFJHHECYFPTfTuDJ7xxuuibFTQmUFu2zjbYfYKhPE=
